import csv
import io
import json
from typing import Any

from app.services import priority_service
from app.knowledge_base.platform_store import read_store
from app.services.time import now_iso


def summary() -> dict[str, int]:
    store = read_store()
    return {
        "circulars": len(store.circulars),
        "verified_rules": len(store.verified_rules),
        "connected_systems": len(store.connected_systems),
        "compliance_findings": len(store.compliance_findings),
        "conflicts": len(store.conflicts),
        "priority_scores": len(store.priority_scores),
    }


def _matches(value: Any, expected: str | None) -> bool:
    return expected in {None, "", value}


def compliance_report(
    service_id: str | None = None,
    severity: str | None = None,
    status: str | None = None,
) -> list[dict[str, Any]]:
    return [
        item.model_dump()
        for item in read_store().compliance_findings
        if _matches(item.service_id, service_id)
        and _matches(item.severity, severity)
        and _matches(item.status, status)
    ]


def conflict_report(
    status: str | None = None,
    severity: str | None = None,
) -> list[dict[str, Any]]:
    return [
        item.model_dump()
        for item in read_store().conflicts
        if _matches(item.status, status) and _matches(item.severity, severity)
    ]


def priority_report(priority_level: str | None = None) -> list[dict[str, Any]]:
    return [
        item.model_dump()
        for item in priority_service.list_priorities()
        if _matches(item.priority_level, priority_level)
    ]


def rules_report(service_id: str | None = None, status: str | None = None) -> list[dict[str, Any]]:
    return [
        item.model_dump()
        for item in read_store().verified_rules
        if _matches(item.service_id, service_id) and _matches(item.status, status)
    ]


def report_rows(report_type: str, filters: dict[str, str | None] | None = None) -> list[dict[str, Any]] | None:
    filters = filters or {}
    reports = {
        "compliance": lambda: compliance_report(
            service_id=filters.get("service_id"),
            severity=filters.get("severity"),
            status=filters.get("status"),
        ),
        "conflicts": lambda: conflict_report(
            status=filters.get("status"),
            severity=filters.get("severity"),
        ),
        "priority": lambda: priority_report(priority_level=filters.get("priority_level")),
        "rules": lambda: rules_report(service_id=filters.get("service_id"), status=filters.get("status")),
    }
    if report_type not in reports:
        return None
    return reports[report_type]()


def report_metadata(report_type: str, filters: dict[str, Any], generated_by: str | None) -> dict[str, Any]:
    rows = report_rows(report_type, filters) or []
    clean_filters = {key: value for key, value in filters.items() if value not in {None, ""}}
    return {
        "generated_at": now_iso(),
        "generated_by": generated_by or "system",
        "report_type": report_type,
        "filters": clean_filters,
        "total_records": len(rows),
    }


def rows_with_metadata(rows: list[dict[str, Any]], metadata: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {
            "generated_at": metadata["generated_at"],
            "generated_by": metadata["generated_by"],
            "report_type": metadata["report_type"],
            "filters": json.dumps(metadata["filters"], sort_keys=True),
            "total_records": metadata["total_records"],
            **row,
        }
        for row in rows
    ]


def to_csv(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=list(rows[0].keys()), extrasaction="ignore")
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()


def to_html(rows: list[dict[str, Any]], metadata: dict[str, Any]) -> str:
    headers = list(rows[0].keys()) if rows else []
    header_html = "".join(f"<th>{header}</th>" for header in headers)
    row_html = "".join(
        "<tr>" + "".join(f"<td>{row.get(header, '')}</td>" for header in headers) + "</tr>"
        for row in rows
    )
    return (
        "<html><body>"
        f"<h1>{metadata['report_type'].title()} Report</h1>"
        f"<p>Generated at: {metadata['generated_at']}</p>"
        f"<p>Generated by: {metadata['generated_by']}</p>"
        f"<p>Total records: {metadata['total_records']}</p>"
        f"<table><thead><tr>{header_html}</tr></thead><tbody>{row_html}</tbody></table>"
        "</body></html>"
    )
