from __future__ import annotations

import json
from pathlib import Path
from uuid import uuid4

from app.models.sandbox_models import SandboxCircular, SandboxCircularCreateRequest
from app.demo.pdf_generator import build_simple_pdf
from app.knowledge_base.platform_store import add_audit_event, read_store, write_store
from app.knowledge_base.circular_ingestion_service import ingest_circular
from app.services.time import now_iso

BASE_DIR = Path(__file__).resolve().parents[1]
STORAGE_DIR = BASE_DIR / "storage"
CIRCULARS_DIR = STORAGE_DIR / "sandbox_circulars"
DATA_PATH = STORAGE_DIR / "sandbox_circulars.json"


def _load_records() -> list[SandboxCircular]:
    if not DATA_PATH.exists():
        return []
    with DATA_PATH.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    return [SandboxCircular(**item) for item in payload.get("circulars", [])]


def _save_records(records: list[SandboxCircular]) -> None:
    STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    with DATA_PATH.open("w", encoding="utf-8") as handle:
        json.dump({"circulars": [item.model_dump() for item in records]}, handle, indent=2)


def _find(circular_id: str) -> SandboxCircular | None:
    return next((item for item in _load_records() if item.id == circular_id), None)


def _build_raw_text(circular: SandboxCircular) -> str:
    return (
        f"{circular.circular_number} {circular.department} circular: "
        f"{circular.title}. {circular.service_affected} {circular.rule_key} changed "
        f"from {circular.old_value} to {circular.new_value}. Effective {circular.effective_date}. "
        f"{circular.body}"
    )


def status() -> dict:
    records = _load_records()
    return {
        "success": True,
        "sandbox": "virtual_government",
        "circular_count": len(records),
        "latest_status": records[-1].delivery_status if records else "none",
    }


def list_circulars() -> dict:
    return {"success": True, "circulars": [item.model_dump() for item in _load_records()]}


def create_circular(payload: SandboxCircularCreateRequest | None = None) -> dict:
    payload = payload or SandboxCircularCreateRequest()
    timestamp = now_iso()
    effective_date = payload.effective_date or timestamp[:10]
    circular = SandboxCircular(
        id=f"sbx_{uuid4().hex[:12]}",
        department=payload.department,
        circular_number=payload.circular_number,
        title=payload.title,
        service_affected=payload.service_affected,
        rule_key=payload.rule_key,
        old_value=payload.old_value,
        new_value=payload.new_value,
        effective_date=effective_date,
        body=payload.body,
        status="draft",
        delivery_status="Draft",
        created_at=timestamp,
        updated_at=timestamp,
    )
    records = _load_records()
    records.append(circular)
    _save_records(records)
    store = read_store()
    add_audit_event(
        store,
        "sandbox_circular_created",
        {
            "entity_type": "sandbox_circular",
            "entity_id": circular.id,
            "circular_number": circular.circular_number,
        },
    )
    write_store(store)
    return {"success": True, "circular": circular.model_dump()}


def generate_pdf(circular_id: str) -> dict:
    circular = _find(circular_id)
    if circular is None:
        return {"success": False, "message": "Sandbox circular not found."}

    CIRCULARS_DIR.mkdir(parents=True, exist_ok=True)
    pdf_name = f"{circular.circular_number.replace('/', '_')}_{circular.id}.pdf"
    pdf_path = CIRCULARS_DIR / pdf_name
    lines = [
        "Virtual Government Sandbox",
        f"Department: {circular.department}",
        f"Circular Number: {circular.circular_number}",
        f"Title: {circular.title}",
        f"Effective Date: {circular.effective_date}",
        f"Field Changed: {circular.rule_key.replace('_', ' ').title()}",
        f"Old Rule: {circular.old_value}",
        f"New Rule: {circular.new_value}",
        f"Affected Service: {circular.service_affected}",
        "",
        circular.body,
        "",
        "Disclaimer: Demo circular generated by Virtual Government Sandbox,",
        "not an official government circular.",
    ]
    pdf_path.write_bytes(build_simple_pdf(lines))

    circular.pdf_path = str(pdf_path.relative_to(BASE_DIR))
    circular.pdf_url = f"/api/sandbox/circulars/{circular.id}/pdf"
    circular.status = "pdf_generated"
    circular.delivery_status = "PDF Generated"
    circular.updated_at = now_iso()

    records = _load_records()
    records = [circular if item.id == circular_id else item for item in records]
    _save_records(records)

    store = read_store()
    add_audit_event(
        store,
        "sandbox_circular_pdf_generated",
        {
            "entity_type": "sandbox_circular",
            "entity_id": circular.id,
            "circular_number": circular.circular_number,
            "pdf_path": circular.pdf_path,
        },
    )
    write_store(store)
    return {
        "success": True,
        "circular_id": circular.id,
        "pdf_url": circular.pdf_url,
        "circular_number": circular.circular_number,
        "circular": circular.model_dump(),
    }


def get_pdf_bytes(circular_id: str) -> tuple[bytes, str] | None:
    circular = _find(circular_id)
    if circular is None or not circular.pdf_path:
        return None
    path = BASE_DIR / circular.pdf_path
    if not path.exists():
        return None
    return path.read_bytes(), f"{circular.circular_number}.pdf"


def export_for_manual_upload(circular_id: str, actor_id: str | None = None) -> dict:
    circular = _find(circular_id)
    if circular is None:
        return {"success": False, "message": "Sandbox circular not found."}
    if circular.status not in {"pdf_generated", "ready_for_manual_upload"}:
        return {"success": False, "message": "Generate PDF before exporting."}

    circular.status = "ready_for_manual_upload"
    circular.delivery_status = "Ready for manual upload"
    circular.updated_at = now_iso()

    records = _load_records()
    records = [circular if item.id == circular_id else item for item in records]
    _save_records(records)

    store = read_store()
    add_audit_event(
        store,
        "sandbox_circular_exported_for_manual_upload",
        {
            "entity_type": "sandbox_circular",
            "entity_id": circular.id,
            "circular_number": circular.circular_number,
            "exported_by": actor_id,
            "manual_upload_required": True,
        },
    )
    write_store(store)
    return {
        "success": True,
        "circular": circular.model_dump(),
        "manual_upload": {
            "required": True,
            "upload_endpoint": "/api/circulars/upload",
            "pdf_url": circular.pdf_url,
            "raw_text": _build_raw_text(circular),
        },
        "integration_event": {
            "type": "sandbox_circular_ready_for_manual_upload",
            "circular_id": circular.id,
        },
    }


def publish_to_government(circular_id: str, actor_id: str | None = None) -> dict:
    circular = _find(circular_id)
    if circular is None:
        return {"success": False, "message": "Sandbox circular not found."}
    if not circular.pdf_path:
        return {"success": False, "message": "Generate PDF before publishing."}

    document, created = ingest_circular(
        {
            "source_id": "virtual_government_sandbox",
            "circular_number": circular.circular_number,
            "title": circular.title,
            "department": circular.department,
            "published_date": circular.created_at[:10],
            "effective_date": circular.effective_date,
            "document_url": None,
            "storage_path": circular.pdf_path,
            "raw_text": _build_raw_text(circular),
        }
    )

    # Government users receive the same generated artifact through their own
    # role-scoped endpoint; the sandbox PDF endpoint remains sandbox-only.
    document.document_url = f"/api/government/circulars/{document.id}/pdf"
    store = read_store()
    stored_document = next((item for item in store.circular_documents if item.id == document.id), None)
    if stored_document:
        stored_document.document_url = document.document_url
    timestamp = now_iso()
    add_audit_event(
        store,
        "sandbox_circular_published",
        {
            "entity_type": "sandbox_circular",
            "entity_id": circular.id,
            "government_document_id": document.id,
            "published_by": actor_id,
        },
    )
    add_audit_event(
        store,
        "government_circular_received",
        {
            "entity_type": "circular_document",
            "entity_id": document.id,
            "sandbox_circular_id": circular.id,
        },
    )
    write_store(store)

    circular.status = "published"
    circular.delivery_status = "Received by NiyamGuard"
    circular.government_document_id = document.id
    circular.published_at = circular.published_at or timestamp
    circular.updated_at = timestamp
    records = [circular if item.id == circular_id else item for item in _load_records()]
    _save_records(records)
    return {
        "success": True,
        "message": "Circular published to the NiyamGuard Government Circular Inbox.",
        "circular": circular.model_dump(),
        "government_document": document.model_dump(),
        "created": created,
        "integration_event": {
            "type": "sandbox_circular_published",
            "circular_id": circular.id,
            "government_document_id": document.id,
        },
    }
